In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("db/tweet/HSpam_dataset1.csv")
df

,id,tweet,no_followers,no_followings,no_userfavorites,no_lists,no_tweets,no_retweets,no_favorites,no_hashtags,no_usermentions,no_urls,label
0,2,That just seriously ruined my night..,163,139,1560,1,25985,0,0,0,0,0,0
1,3,@JessleaC I no they are so funny ..! I love yo...,113,197,1072,1,2142,0,0,0,1,0,0
2,5,@honkwas might drive so we could go subway or ...,168,382,1732,1,3493,0,0,0,1,0,0
3,9,That @brad_frost post is bourne out by my expe...,285,596,5765,45,8670,0,0,0,1,0,0
4,10,why tf do i keep waking up every 2 hours -.-,631,353,1589,2,12285,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,190,If I wanted to read your convo I would click o...,252,270,4885,2,10769,0,0,0,0,0,0
99,192,@OMGFacts I find a decent pair of #Jockeys wil...,75,335,382,2,3020,0,0,1,1,0,0
100,193,hmm stupid ass alarm got me liking country music.,502,593,16586,1,17345,0,0,0,0,0,0
101,195,"_/|\_ YOU yourself, as much as anybody in the...",1433,1582,1281,52,20601,0,0,1,0,0,0
102,196,What keeps me busy on a thursday afternoon ðŸ’… #...,1733,612,9075,3,69891,0,0,6,0,1,0