In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [8]:
df = pd.read_csv("tweet_dataset.csv")
df

,id,tweet,no_followers,no_followings,no_userfavorites,no_lists,no_tweets,no_retweets,no_favorites,no_hashtags,no_usermentions,no_urls,label
0,2,That just seriously ruined my night..,163,139,1560,1,25985,0,0,0,0,0,0
1,3,@JessleaC I no they are so funny ..! I love yo...,113,197,1072,1,2142,0,0,0,1,0,0
2,5,@honkwas might drive so we could go subway or ...,168,382,1732,1,3493,0,0,0,1,0,0
3,9,That @brad_frost post is bourne out by my expe...,285,596,5765,45,8670,0,0,0,1,0,0
4,10,why tf do i keep waking up every 2 hours -.-,631,353,1589,2,12285,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007996,2961809,I just reached level 78 in The Tribez! Join in...,2,6,0,0,13562,0,0,3,0,1,1
1007997,2961810,Ima smash on site when I get that bitch,477,588,7048,0,18346,0,0,0,0,0,0
1007998,2961811,RT @NiallOfficial: Pukin on fans hahahaha! Whe...,663,476,9079,4,36930,40219,0,0,1,0,0
1007999,2961812,we should of had Monday off,297,1436,5815,0,5308,0,0,0,0,0,0
1008000,2961814,Cancer Care Insights: Cancer care in Florida: ...,213,251,0,0,12790,0,0,0,0,1,0

# data preprocessing

In [9]:
# data preprocessing
from string import punctuation
from nltk.corpus import stopwords

In [10]:
df["tweet_clean"] = df["tweet"]
df

,id,tweet,no_followers,no_followings,no_userfavorites,no_lists,no_tweets,no_retweets,no_favorites,no_hashtags,no_usermentions,no_urls,label,tweet_clean
0,2,That just seriously ruined my night..,163,139,1560,1,25985,0,0,0,0,0,0,That just seriously ruined my night..
1,3,@JessleaC I no they are so funny ..! I love yo...,113,197,1072,1,2142,0,0,0,1,0,0,@JessleaC I no they are so funny ..! I love yo...
2,5,@honkwas might drive so we could go subway or ...,168,382,1732,1,3493,0,0,0,1,0,0,@honkwas might drive so we could go subway or ...
3,9,That @brad_frost post is bourne out by my expe...,285,596,5765,45,8670,0,0,0,1,0,0,That @brad_frost post is bourne out by my expe...
4,10,why tf do i keep waking up every 2 hours -.-,631,353,1589,2,12285,0,0,0,0,0,0,why tf do i keep waking up every 2 hours -.-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007996,2961809,I just reached level 78 in The Tribez! Join in...,2,6,0,0,13562,0,0,3,0,1,1,I just reached level 78 in The Tribez! Join in...
1007997,2961810,Ima smash on site when I get that bitch,477,588,7048,0,18346,0,0,0,0,0,0,Ima smash on site when I get that bitch
1007998,2961811,RT @NiallOfficial: Pukin on fans hahahaha! Whe...,663,476,9079,4,36930,40219,0,0,1,0,0,RT @NiallOfficial: Pukin on fans hahahaha! Whe...
1007999,2961812,we should of had Monday off,297,1436,5815,0,5308,0,0,0,0,0,0,we should of had Monday off
1008000,2961814,Cancer Care Insights: Cancer care in Florida: ...,213,251,0,0,12790,0,0,0,0,1,0,Cancer Care Insights: Cancer care in Florida: ...

In [11]:
# Preprocessing techniques
def remove_stop_words(text):
    """Remove stop words"""
    nltk_stop = stopwords.words("english")
    text = " ".join([c for c in text.split() if c not in nltk_stop])
    return text


def remove_unicode(text):
    """ Removes unicode strings like "\u002c" and "x96" """
    text = re.sub(r"(\\u[0-9A-Fa-f]+)", r"", text)
    text = re.sub(r"[^\x00-\x7f]", r"", text)
    return text


def remove_url(text):
    """ Replaces url address with "url" """
    text = re.sub("((www\.[^\s]+)|(https?://[^\s]+))", "", text)
    return text


def remove_hashtag(text):
    """ Removes hastag in front of a word """
    text = re.sub(r"#([^\s]+)", r"\1", text)
    return text


def remove_numbers(text):
    """ Removes integers """
    text = "".join([i for i in text if not i.isdigit()])
    return text


def remove_emoticons(text):
    """ Removes emoticons from text """
    text = re.sub(
        ":\)|;\)|:-\)|\(-:|:-D|=D|:P|xD|X-p|\^\^|:-*|\^\.\^|\^\-\^|\^\_\^|\,-\)|\)-:|:'\(|:\(|:-\(|:\S|T\.T|\.\_\.|:<|:-\S|:-<|\*\-\*|:O|=O|=\-O|O\.o|XO|O\_O|:-\@|=/|:/|X\-\(|>\.<|>=\(|D:",
        "",
        text,
    )
    return text


def remove_punctuation(text):
    """remove punctuation"""
    text = text.translate(str.maketrans("", "", punctuation))
    return text

In [12]:
# lower case
print("lowerring case...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: str(x).lower())
# remove unicode
print("removing unicode...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: remove_unicode(x))
# remove url
print("removing url...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: remove_url(x))
# removes hastag in front of a word
print("removing hastag in front of a word...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: remove_hashtag(x))
# removes emoticons from tweet
print("removing emoticons from tweet...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: remove_emoticons(x))
# remove punctuation
print("removing punctuation...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: remove_punctuation(x))
# remove stop words
print("removing stop words...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: remove_stop_words(x))
# removes integers
print("removing integers...")
df["tweet_clean"] = df["tweet_clean"].apply(lambda x: remove_numbers(x))
df

lowerring case...
removing unicode...
removing url...
removing hastag in front of a word...
removing emoticons from tweet...
removing punctuation...
removing stop words...
removing integers...

,id,tweet,no_followers,no_followings,no_userfavorites,no_lists,no_tweets,no_retweets,no_favorites,no_hashtags,no_usermentions,no_urls,label,tweet_clean
0,2,That just seriously ruined my night..,163,139,1560,1,25985,0,0,0,0,0,0,seriously ruined night
1,3,@JessleaC I no they are so funny ..! I love yo...,113,197,1072,1,2142,0,0,0,1,0,0,jessleac funny love pictures take really good ...
2,5,@honkwas might drive so we could go subway or ...,168,382,1732,1,3493,0,0,0,1,0,0,honkwas might drive could go subway mcdonalds ...
3,9,That @brad_frost post is bourne out by my expe...,285,596,5765,45,8670,0,0,0,1,0,0,bradfrost post bourne experience current proje...
4,10,why tf do i keep waking up every 2 hours -.-,631,353,1589,2,12285,0,0,0,0,0,0,tf keep waking every hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007996,2961809,I just reached level 78 in The Tribez! Join in...,2,6,0,0,13562,0,0,3,0,1,1,reached level tribez join try overtake ipad i...
1007997,2961810,Ima smash on site when I get that bitch,477,588,7048,0,18346,0,0,0,0,0,0,ima smash site get bitch
1007998,2961811,RT @NiallOfficial: Pukin on fans hahahaha! Whe...,663,476,9079,4,36930,40219,0,0,1,0,0,rt niallofficial pukin fans hahahaha come
1007999,2961812,we should of had Monday off,297,1436,5815,0,5308,0,0,0,0,0,0,monday
1008000,2961814,Cancer Care Insights: Cancer care in Florida: ...,213,251,0,0,12790,0,0,0,0,1,0,cancer care insights cancer care florida one s...

## Organize cols

In [13]:
def move_column_last_to_first(df):
    # move the last column to the first
    try: 
        cols = df.columns.tolist()
        update_cols = [cols[1]]  # tweet as the first col
        update_cols.append(cols[-1])  # append tweet_clean as second cols
        update_cols.extend(cols[2:-1])  # append tweet_clean as second cols
        df = df[update_cols]
    except Exception as e:
        print(e)
        print("Failed to move columns")
    return df

In [14]:
df_clean = move_column_last_to_first(df)
df_clean

,tweet,tweet_clean,no_followers,no_followings,no_userfavorites,no_lists,no_tweets,no_retweets,no_favorites,no_hashtags,no_usermentions,no_urls,label
0,That just seriously ruined my night..,seriously ruined night,163,139,1560,1,25985,0,0,0,0,0,0
1,@JessleaC I no they are so funny ..! I love yo...,jessleac funny love pictures take really good ...,113,197,1072,1,2142,0,0,0,1,0,0
2,@honkwas might drive so we could go subway or ...,honkwas might drive could go subway mcdonalds ...,168,382,1732,1,3493,0,0,0,1,0,0
3,That @brad_frost post is bourne out by my expe...,bradfrost post bourne experience current proje...,285,596,5765,45,8670,0,0,0,1,0,0
4,why tf do i keep waking up every 2 hours -.-,tf keep waking every hours,631,353,1589,2,12285,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007996,I just reached level 78 in The Tribez! Join in...,reached level tribez join try overtake ipad i...,2,6,0,0,13562,0,0,3,0,1,1
1007997,Ima smash on site when I get that bitch,ima smash site get bitch,477,588,7048,0,18346,0,0,0,0,0,0
1007998,RT @NiallOfficial: Pukin on fans hahahaha! Whe...,rt niallofficial pukin fans hahahaha come,663,476,9079,4,36930,40219,0,0,1,0,0
1007999,we should of had Monday off,monday,297,1436,5815,0,5308,0,0,0,0,0,0
1008000,Cancer Care Insights: Cancer care in Florida: ...,cancer care insights cancer care florida one s...,213,251,0,0,12790,0,0,0,0,1,0

In [16]:
f = "clean_tweet_dataset.csv"
df_clean.to_csv(f, index=False)